image: adoptopenjdk:15.0.2_7-jdk-hotspot

stages:
  - build
  - docs

build:
  stage: build
  script:
    - addgroup --system --gid 1001 build
    - adduser  --system --uid  1001   --group build
    - su build -s /bin/sh -c ""./gradlew detekt jacocoTestReport jacocoTestCoverageVerification jacocoAggregatedReport"
    - mv build/reports/jacoco/jacocoAggregatedReport/html/* docs
    - 'cat ''docs/index.html'' | sed -n ''s/.*Total[^%]*>\([0-9]*%\).*/Coverage: \1/pg'''
  coverage: /Coverage[^0-9]*([0-9]{1,3})%/
  artifacts:
    paths:
      - docs

pages:
  stage: docs
  script:
    - mv docs public
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
