image: adoptopenjdk:15.0.2_7-jdk-hotspot

stages:
  - build
  - docs

build:
  stage: build
  script:
    - ./gradlew detekt jacocoTestReport jacocoTestCoverageVerification jacocoAggregatedReport
    - mv build/reports/jacoco/jacocoAggregatedReport/html/* docs
    - 'cat ''docs/index.html'' | sed -n ''s/.*Total[^%]*>\([0-9]*%\).*/Coverage: \1/pg'''
  coverage: /Coverage[^0-9]*([0-9]{1,3})%/
  artifacts:
    paths:
      - docs

pages:
  stage: docs
  script:
    - mv docs pages
  artifacts:
    paths:
      - pages
    expire_in: 1 day
  only:
    - master
